name: app
description: A new Flutter project.
version: 1.0.1+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  youtube_player_flutter: ^4.1.0
  font_awesome_flutter: ^8.5.0
  toast: ^0.1.5
  url_launcher: ^5.1.2
  webview_flutter: ^0.3.14
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/jsons/
    - assets/images/